baseurl = "https://alemorm.github.io/ucsf-radiology-getting-started/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "docs"
title = "Getting Started"
canonifyurls  = true
enableGitInfo = true
googleAnalytics = "UA-168924327-1"

DefaultContentLanguage = "en"
theme = ["hugo-notice", "beautifulhugo"]
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true


[Params]
  subtitle = "UCSF Radiology Getting Started Guide"
#   logo = "materials/UCSF_sig_navy_RGB.png"
  favicon = "materials/GitHub-Mark-Light-32px.png"
  dateFormat = "January 2, 2006"
  commit = "https://github.com/alemorm/ucsf-radiology-getting-started/tree/"
  rss = false
  comments = true
#   gcse = "002827558899377173796:mvr9v8sqbnq" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

# [[Params.bigimg]]
#  src = "materials/UCSF_sig_navy_RGB.png"
#  src = "img/UCSF_sig_navy_RGB.png"
#  src = "img/triangle.jpg"
#  src = "img/UCSF_sublogo_RadiologyBiomedicalImaging_navy_RGB.png"
#  desc = "Triangle"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
# [[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Alejandro Morales Martinez"
  email = "alejandro.moralesmartinez@ucsf.edu"
  gitlab = "amoralesmartinez"
  github = "alemorm"
  linkedin = "alegmoralesm"
  
[[menu.main]]
    identifier = "Education"
    name = "Education"
    weight = 1

[[menu.main]]
    parent = "Education"
    name = "MRI"
    url = "/page/mriedu"
    weight = 1

[[menu.main]]
    parent = "Education"
    name = "Linux"
    url = "/page/linuxedu"
    weight = 2

[[menu.main]]
    parent = "Education"
    name = "Git"
    url = "/page/gitedu"
    weight = 3

[[menu.main]]
    parent = "Education"
    name = "Machine Learning"
    url = "/page/machinelearningedu"
    weight = 4

[[menu.main]]
    identifier = "Radiology"
    name = "Radiology"
    weight = 2

[[menu.main]]
    parent = "Radiology"
    name = "Onboarding"
    url = "/page/onboarding"
    weight = 1
    
[[menu.main]]
    parent = "Radiology"
    name = "Server Access"
    url = "/page/serverinfo"
    weight = 2

[[menu.main]]
    parent = "Radiology"
    name = "SSH"
    url = "/page/sshinfo"
    weight = 3

[[menu.main]]
    parent = "Radiology"
    name = "VNC"
    url = "/page/vncinfo"
    weight = 4

[[menu.main]]
    identifier = "Tools"
    name = "Tools"
    weight = 3

[[menu.main]]
    parent = "Tools"
    name = "Matlab"
    url = "/page/matlabinfo"
    weight = 1

[[menu.main]]
    parent = "Tools"
    name = "Python"
    url = "/page/pythoninfo"
    weight = 2

[[menu.main]]
    parent = "Tools"
    name = "Jupyter"
    url = "/page/jupyterinfo"
    weight = 3

[[menu.main]]
    parent = "Tools"
    name = "Deep Learning"
    url = "/page/deeplearninginfo"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4